# Generated by Django 3.1.7 on 2021-07-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(default='Country Name', max_length=200)),
                ('csv_file', models.FileField(upload_to='country_csvs')),
            ],
        ),
    ]
